### ISSUE TITLE
Can you add support for restructuredText table?

### ISSUE THREAD

**Issue by AzureRabbit** [stormherz/tablify#1]
Can you add support for restructuredText table?
header delimiter like this:
+----------------------------+---------------------------+
| Column1                      |  Column 2                   |
+==================+=================+

**Comment by stormherz** [comment]
@octodile I'm not using VIM anymore, but I'll take a look, guess that won't be a big change

**Comment by stormherz** [comment]
@octodile I've updated the plugin, it should generate correct rst table headers. Plugin now automatically switches to rst mode in `*.rst` buffers, but rst mode can also can be enabled manually, by setting `b:tablify_restructuredtext` to `1`

**Comment by AzureRabbit** [comment]
Thank you very much!
