### ISSUE TITLE
align right and center not working at 904cfd4

### ISSUE THREAD

**Issue by aeiouaoeiuv** [stormherz/tablify#2]
Hi, @stormherz . Aligning right and center not working, only aligning left is avaialble(version  904cfd4, the newest version for now).

And, older version(0434ac1) is working.

Could you fix that?

**Comment by stormherz** [comment]
@aeiouaoeiuv I'll see what I can do. I'm not working with VIM anymore, so it might take some time

**Comment by stormherz** [comment]
@aeiouaoeiuv it was simpler than I thought, just a missing alignment parameter. Should be fixed now. Thanks for creating an issue =)
